Use geocodeio
RagtagOpen/match-district pull request #7
Opened 2018-03-01 05:11 UTC by iandees

A first stab at switching over to geocode.io to do district lookup.

2018-03-01 05:11 UTC, iandees commented
This isn't ready to go yet… I haven't tested it yet and I'm not sure what the input or output data is supposed to look like.

2018-03-01 23:26 UTC, jillh510 requested changes

2018-03-01 23:26 UTC, jillh510 commented on index.html
> +            var stateName = jsonResults[0].address_componenets.state;
is it really spelled componenets?

2018-03-01 23:44 UTC, iandees commented on index.html
> +            var stateName = jsonResults[0].address_componenets.state;
Hah, nope.

2018-03-02 03:25 UTC, iandees commented
This is ready to go, @jillh510. Tested it locally and it works well for me, including the case of not finding a matching zipcode.

2018-03-03 21:00 UTC, jillh510 approved these changes

2018-03-03 21:02 UTC, merged